dist: xenial
sudo: false
language: python

python:
  - "3.6"

cache:
  - pip
  - apt

addons:
  postgresql: '9.4'

before_install:
  # bust only the the part of the cache that we are frequently changing
  - pip uninstall --yes gdcdictionary gdcdatamodel || true
  # resolve https://github.com/travis-ci/travis-ci/issues/7940
  - export BOTO_CONFIG=/dev/null

# command to install dependencies
install:
  - pip install poetry
  - poetry install -vv --no-interaction

before_script:
  - poetry run python bin/setup_test_database.py
  - mkdir -p tests/resources/keys; cd tests/resources/keys; openssl genrsa -out test_private_key.pem 2048; openssl rsa -in test_private_key.pem -pubout -out test_public_key.pem; cd -

# command to run tests
script:
  - poetry run pytest -vv --cov=peregrine --cov-report xml tests

after_script:
  - python-codacy-coverage -r coverage.xml

env:
  global:
    - GDC_ES_HOST=localhost
