sudo: false
dist: trusty
group: deprecated-2017Q2
language: python

python:
  - "2.7"

cache:
  # pip: true  # We have overridden the default install step, caching manually
  # ref: <https://docs.travis-ci.com/user/caching/#Arbitrary-directories>
  - directories:
      - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
      - $HOME/.pip-cache
  - apt

addons:
  postgresql: '9.4'
  # fix for scipy inside SurvivalPy
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

services:
  - elasticsearch
  - docker

before_install:
  # bust only the the part of the cache that we are frequently changing
  - pip uninstall --yes psqlgraph gdcdictionary gdcdatamodel || true


# command to install dependencies
install:
  # fix for scipy inside SurvivalPy
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy nose future

  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

before_script:
  - psql -c "create database test_userapi" -U postgres
  - userdatamodel-init --db test_userapi
  - pip freeze
  - python bin/setup_test_database.py

# command to run tests
script:
- |
  set -e
  PYTHONPATH=. py.test -vv tests/system_test.py tests/graphql/test_graphql.py
  set +e
env:
  global:
    - GDC_ES_HOST=localhost
